### ISSUE TITLE
`npm test` throws errors

### ISSUE THREAD

**Issue by axlf** [zurb/foundation-emails#29]
Hey, 

I'm trying to run `npm test` on my Mac Host but it throws errors.

```
#npm test

> foundation-emails@2.0.0-alpha test /Users/alexander/Code/foundation-emails
> cd testing && npm start


> foundation-emails-template@0.0.1 start /Users/alexander/Code/foundation-emails/testing
> gulp

[22:08:23] Requiring external module babel-register
[22:08:23] Using gulpfile ~/Code/foundation-emails/testing/gulpfile.babel.js
[22:08:23] Starting 'default'...
[22:08:23] Starting 'build'...
[22:08:23] Starting 'clean'...
[22:08:23] Finished 'clean' after 2.22 ms
[22:08:23] Starting 'copy'...
[22:08:23] Finished 'copy' after 12 ms
[22:08:23] Starting 'pages'...
[22:08:24] 'pages' errored after
[22:08:24] TypeError: (0 , _inky2.default) is not a function
    at pages (gulpfile.babel.js:35:11)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at asyncRunner (/Users/alexander/Code/foundation-emails/testing/node_modules/async-done/index.js:36:18)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickDomainCallback (node.js:422:13)
[22:08:24] 'build' errored after
[22:08:24] 'default' errored after

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.4.1_1/bin/node" "/Users/alexander/.npm-packages/bin/npm" "start"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! foundation-emails-template@0.0.1 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-emails-template@0.0.1 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foundation-emails-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foundation-emails-template
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foundation-emails-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alexander/Code/foundation-emails/testing/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

Following versions are installed:
```
#node -v
v5.4.1
#npm -v
3.5.3
```

Any ideas?

Thanks

**Comment by gakimball** [comment]
Could you try setting up our new [template stack](https://github.com/zurb/foundation-emails-template) and see how it works for you? The errors you're getting are related to the Inky dependency not being up to date, and this template has been configured to use the latest version of everything.

It's the same as the one in the `testing/` folder, but standalone.
